### ISSUE TITLE
Terminal::new returns Err in the git-bash on Windows 7

### ISSUE THREAD

**Issue by Cryptjar** [murarth/mortal#6]
Using the `Terminal::new()` on Windows (7 at least) is incompatible with the `git-bash` [1] terminal (which is part of the `git` distribution on Windows). The following program could be compiled using the Windows native MSVC tool chain on Windows (also using the git-bash) and cross-compiled using the GUN tool chain and Linux (I haven't tried further combinations).
Both binaries work as expected using the Windows `cmd.exe`. However, executing either binary from within the `git-bash` results in a panic indicating an invalid terminal. The panic occurs even when executing the binaries form the `cmd.exe` running within the `git-bash`. 

As a side note, when using other Rust terminal interface libraries (such as `crossterm` [2]), which use the ANSI escape sequences, a similar program would work in both terminals. However, due to the limited support of such escape sequences in `cmd.exe` usage of some styles results in clobbered output, while the `git-bash` seems to have sufficient support for them.

[1]: https://git-scm.com/download/win
[2]: https://crates.io/crates/crossterm

---

System:
```
windows 7 (64-bit)
```

Arch:
```
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
```

Steps to reproduce (executing in the git-bash):
```
$ RUST_BACKTRACE=1 cargo run --target x86_64-pc-windows-msvc
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target\x86_64-pc-windows-msvc\debug\mortal-git-bash.exe`
Hello, world!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "The handle is invalid." }', src\libcore\result.rs:1009:5
stack backtrace:
   0: std::sys_common::backtrace::_print
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\sys_common\backtrace.rs:71
   1: std::panicking::default_hook::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\panicking.rs:211
   2: std::panicking::default_hook
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\panicking.rs:227
   3: std::panicking::rust_panic_with_hook
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\panicking.rs:491
   4: std::panicking::continue_panic_fmt
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\panicking.rs:398
   5: std::panicking::rust_begin_panic
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\panicking.rs:325
   6: core::panicking::panic_fmt
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libcore\panicking.rs:95
   7: core::result::unwrap_failed<std::io::error::Error>
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libcore\macros.rs:26
   8: core::result::Result<mortal::terminal::Terminal, std::io::error::Error>::unwrap<mortal::terminal::Terminal,std::io::error::Error>
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libcore\result.rs:808
   9: mortal_git_bash::main
             at .\src\main.rs:3
  10: std::rt::lang_start::{{closure}}<()>
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libstd\rt.rs:74
  11: std::panicking::try::do_call<closure,i32>
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\panicking.rs:310
  12: panic_unwind::__rust_maybe_catch_panic
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libpanic_unwind\lib.rs:102
  13: std::rt::lang_start_internal
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\/src\libstd\rt.rs:58
  14: std::rt::lang_start<()>
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libstd\rt.rs:74
  15: main
  16: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  17: BaseThreadInitThunk
  18: RtlUserThreadStart
error: process didn't exit successfully: `target\x86_64-pc-windows-msvc\debug\mortal-git-bash.exe` (exit code: 101)
```

```
$ RUST_BACKTRACE=1 ./mortal-git-bash-gun.exe
Hello, world!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "The handle is invalid." }', src\libcore\result.rs:1009:5
stack backtrace:
   0: std::sys_common::backtrace::_print
             at src\libstd\sys\windows\backtrace/mod.rs:104
             at src\libstd\sys\windows\backtrace/mod.rs:95
             at src\libstd\sys_common/backtrace.rs:71
   1: std::panicking::default_hook::{{closure}}
             at src\libstd\sys_common/backtrace.rs:59
             at src\libstd/panicking.rs:211
   2: std::panicking::default_hook
             at src\libstd/panicking.rs:227
   3: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:491
   4: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:398
   5: rust_begin_unwind
             at src\libstd/panicking.rs:325
   6: core::panicking::panic_fmt
             at src\libcore/panicking.rs:95
   7: core::result::unwrap_failed
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libcore\macros.rs:26
   8: <core::result::Result<T, E>>::unwrap
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libcore\result.rs:808
   9: mortal_git_bash::main
             at src/main.rs:3
  10: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libstd\rt.rs:74
  11: std::panicking::try::do_call
             at src\libstd/rt.rs:59
             at src\libstd/panicking.rs:310
  12: _rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:102
  13: std::rt::lang_start_internal
             at src\libstd/panicking.rs:289
             at src\libstd/panic.rs:398
             at src\libstd/rt.rs:58
  14: std::rt::lang_start
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libstd\rt.rs:74
  15: main
  16: _tmainCRTStartup
  17: mainCRTStartup
  18: unit_addrs_search
  19: unit_addrs_search
```

src/main.rs:
```rust
fn main() {
    println!("Hello, world!");
    let t = mortal::Terminal::new().unwrap();
    t.write_str("Mortal\n");
    std::thread::sleep_ms(5_000);
}
```

Cargo.toml:
```
[package]
name = "mortal-git-bash"
version = "0.1.0"
edition = "2018"

[dependencies]
mortal="0.1.5"
```

**Comment by murarth** [comment]
On Windows, `mortal` uses the Windows console API to interface with the console. I'm not familiar with `git-bash`, but it appears that it doesn't present a Windows console with which to interact. That's why `mortal` fails to create a valid handle.

On Unix, the `terminfo` crate is used to read terminfo database files, which tell `mortal` which escape sequences to use to perform functions. `mortal` does not hard-code ANSI escape sequences.

The `terminfo` method could be used with `git-bash`, if `git-bash` (or some other software package) provides a terminfo database.

**Comment by Cryptjar** [comment]
Actually, `git-bash` provides the `terminfo` database required by the `terminfo` crate. However, as the `terminfo` crate specifies in their repository Readme file it can't be trivially located on default:

> Unfortunately, if you're using a non-windows console on Windows (e.g. MinGW, Cygwin, Git Bash), you'll need to set the TERMINFO environment variable to point to the directory containing the terminfo database.

Yet, if the `TERMINFO` variable is correctly set (e.g. by the user), the `terminfo` crate is able to access the required information. So, it might be worth on Windows to check after the WinAPI approach failed if `terminfo` can locate any terminal-database and if so use it as a fallback. Unfortunatly, adding the `terminfo` dependency seems to add several third party crates. If too many dependencies is a concern, it could be an option to provided this fallback via a (non-default) feature in Mortal.

**Comment by Cryptjar** [comment]
Since Win7 is deprecated, and I don't use Windows anymore, I don't see any point in this issue anymore.
